"""empty message

Revision ID: 09aaf123439e
Revises: 329f22f69f5e
Create Date: 2022-11-08 09:10:58.748801

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '09aaf123439e'
down_revision = '329f22f69f5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transacs_ibfk_1', 'transacs', type_='foreignkey')
    op.drop_column('transacs', 'acc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transacs', sa.Column('acc', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('transacs_ibfk_1', 'transacs', 'accs', ['acc'], ['id'])
    # ### end Alembic commands ###
