"""empty message

Revision ID: 46986bbbd2b8
Revises: 721a5e89bf23
Create Date: 2022-11-03 09:36:03.711179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46986bbbd2b8'
down_revision = '721a5e89bf23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('commenter_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'users', ['commenter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'commenter_id')
    # ### end Alembic commands ###
