"""empty message

Revision ID: 721a5e89bf23
Revises: 5e0cf6b0ef78
Create Date: 2022-11-03 09:30:14.008421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '721a5e89bf23'
down_revision = '5e0cf6b0ef78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
