"""empty message

Revision ID: 9be264db1b55
Revises: 46986bbbd2b8
Create Date: 2022-11-08 05:27:06.467077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9be264db1b55'
down_revision = '46986bbbd2b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acc_no', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=4096), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('address', sa.String(length=4096), nullable=True),
    sa.PrimaryKeyConstraint('id', 'acc_no')
    )
    op.create_table('transacs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('transacid', sa.Integer(), nullable=True),
    sa.Column('ruleid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ruleid'], ['rules.id'], ),
    sa.ForeignKeyConstraint(['transacid'], ['transacs.id'], ),
    sa.PrimaryKeyConstraint('id', 'issue_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('transacs')
    op.drop_table('accs')
    # ### end Alembic commands ###
